-- Migration 021: Seed Typing Test Questions
-- Module: Tes Mengetik (Wowin Purnomo Putera)

INSERT INTO modules (id, name, description, total_weight, created_by)
VALUES ('33333333-4444-4444-4444-555555555555', 'Tes Mengetik', 'Tes kecepatan dan ketepatan mengetik dengan konten profil perusahaan.', 100.00, '22222222-2222-2222-2222-222222222222')
ON CONFLICT (id) DO NOTHING;

INSERT INTO questions (id, module_id, type, content, weight, requires_manual_review, timer_limit)
VALUES 
  (gen_random_uuid(), '33333333-4444-4444-4444-555555555555', 'typing_test', 'PT Wowin Purnomo Putera merupakan perusahaan yang bergerak di bidang distribusi dan operasional penjualan dengan fokus pada efisiensi kerja, ketepatan laporan, serta pelayanan kepada pelanggan. Setiap karyawan diharapkan mampu bekerja secara disiplin, menjaga komunikasi antar divisi, dan memahami alur operasional perusahaan. Dalam kegiatan sehari-hari, koordinasi antara tim gudang, sales, administrasi, dan manajemen sangat penting untuk memastikan seluruh proses berjalan dengan baik dan tepat waktu. Perusahaan juga terus mendorong penggunaan teknologi digital untuk meningkatkan produktivitas kerja dan mempermudah proses monitoring operasional.', 20.0, false, 180),
  (gen_random_uuid(), '33333333-4444-4444-4444-555555555555', 'typing_test', 'Divisi gudang memiliki tanggung jawab penting dalam menjaga ketersediaan stok barang dan memastikan proses keluar masuk barang tercatat dengan benar. Setiap barang yang diterima wajib diperiksa kondisi fisik dan jumlahnya sebelum dimasukkan ke dalam sistem. Tim gudang juga harus melakukan pengecekan stok secara berkala untuk menghindari selisih data antara sistem dan kondisi nyata di lapangan. Ketelitian, kecepatan, dan tanggung jawab menjadi hal utama dalam pekerjaan operasional gudang agar distribusi barang kepada pelanggan dapat berjalan lancar tanpa hambatan.', 20.0, false, 180),
  (gen_random_uuid(), '33333333-4444-4444-4444-555555555555', 'typing_test', 'PT Wowin Purnomo Putera menggunakan sistem HRIS untuk membantu pengelolaan data karyawan dan aktivitas operasional harian. Melalui aplikasi tersebut, karyawan dapat melakukan clock in dan clock out menggunakan selfie serta lokasi GPS untuk memastikan validitas kehadiran. Selain itu, aplikasi juga menyediakan fitur pengajuan cuti, izin, lembur, reimbursement, dan pengumuman perusahaan. Dengan adanya sistem digital ini, proses administrasi menjadi lebih cepat, transparan, dan mudah dipantau oleh pihak manajemen maupun karyawan.', 20.0, false, 180),
  (gen_random_uuid(), '33333333-4444-4444-4444-555555555555', 'typing_test', 'Tim sales memiliki peran penting dalam menjaga hubungan baik dengan pelanggan dan meningkatkan penjualan perusahaan. Setiap sales diwajibkan memahami produk yang dijual, menjaga komunikasi yang sopan, serta memberikan pelayanan terbaik kepada pelanggan. Selain melakukan kunjungan rutin, tim sales juga harus membuat laporan aktivitas harian secara tepat waktu melalui sistem perusahaan. Evaluasi performa dilakukan secara berkala untuk memastikan target penjualan tercapai dan kualitas pelayanan tetap terjaga dengan baik.', 20.0, false, 180),
  (gen_random_uuid(), '33333333-4444-4444-4444-555555555555', 'typing_test', 'Budaya kerja di PT Wowin Purnomo Putera menekankan sikap disiplin, tanggung jawab, kerja sama tim, dan kemampuan beradaptasi terhadap perkembangan teknologi. Perusahaan percaya bahwa lingkungan kerja yang positif dapat meningkatkan produktivitas dan kualitas pekerjaan seluruh karyawan. Oleh karena itu, setiap individu diharapkan mampu menjaga etika kerja, menghormati sesama rekan kerja, serta aktif memberikan solusi terhadap permasalahan operasional yang terjadi di lapangan. Dengan semangat kerja sama dan inovasi, perusahaan terus berkembang untuk mencapai target yang lebih besar di masa depan.', 20.0, false, 180)
ON CONFLICT (id) DO NOTHING;
